# Generated by Django 2.0.2 on 2018-02-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mamandyk',
            name='isbn',
            field=models.CharField(help_text=' ', max_length=15, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='mamandyk',
            name='summary',
            field=models.TextField(help_text=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='kafedra',
            name='name',
            field=models.CharField(help_text=' ', max_length=200),
        ),
    ]
